language: go
go:
- 1.6
script: make
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libogg-dev libvorbis-dev libtheora-dev
before_deploy: mkdir -p upload && mkdir -p pkg && cp libshout/src/.libs/libshout.o
  pkg/ && cp iceshift pkg/ && cd pkg && tar -zcvf ../upload/iceshift-${TRAVIS_COMMIT}.tgz
  && echo ${TRAVIS_COMMIT} > ../upload/latest
deploy:
  provider: s3
  access_key_id: AKIAIHZKDSWU6PBCT72Q
  bucket: s3.lstoll.net
  local_dir: upload
  upload_dir: artifacts/iceshift
  acl: public_read
  skip_cleanup: true
  on:
    repo: lstoll/iceshift
    branch: master
  secret_access_key:
    secure: cJ4EdHZR691COy7Yd/S79wLJwc4A0jV73jXl1570md9hhfNOja//XEf8ULD2wabeqbTBps4Zhp2QpKr9iMLRpvyaECkYd41k/+EZKFZJcPP1EdfVKVSXkUMsSK8emGwjcrvlPhrS50Uco+rbmo/litjD8Gt/uTzT92jJw/xb5FgeSrKiSYdk0h69tAO0FAvnKg8kWnwBv6OaGIDkob5HyusNmSWuMZnN72VntLDyhkVoLTpGQO6UFTA+D9Je7O65/XGqs6JrVTDAjbnsjpmM7STPkZAERlbNpFduAa8OD5ZX/dxndL2W6+Q+pdghxMa3zRHlH3I60DM6GR/yRNL5l+A7brA5x3Vq6bIc+Ssi8yxMMX3VDM1atJynQT1w2nMfEpnKXoUGXfvsI4SXhmGDi4CBoVFpIHBXSDpKh22cKIImdddTMcuRfr/apw/NErPB3Pk/AXJuse+EAx2tpTLdIB2ASbxzlRMrs8E+02o6zAWXKHJ2Xku4sYq2Z0TL9VGt735uY68c2GRPthys0dCksgIRVbbYuKmaKZc+GsBjxTtH7NNTZmYpI8LU+KPAbiy1XT091/ZQ68wNpZ5ml4SJifucWuDiPoxw5WNK1GL7B7mTAcg88gIQi0ofMu5hijdG6TwfR+hJ323FQcMGqI2B3MtOhGXfUX7/qMHeejHJkMg=
